django_cd/urls.py
""""""

# Standard library modules.

# Third party modules.
from django.urls import path

# Local modules.
from . import views

# Globals and constants variables.

app_name = "django_cd"
urlpatterns = [
    path("", views.index, name="index"),
    path("jobruns", views.jobruns, name="jobruns"),
    path("jobruns/<int:id>", views.jobrun, name="jobrun"),
    path("runjob", views.runjob, name="runjob"),
]

django_cd/models.py
""""""

# Standard library modules.

# Third party modules.
from django.db import models

# Local modules.

# Globals and constants variables.


class RunState(models.TextChoices):
    NOT_STARTED = "not started"
    RUNNING = "running"
    ERROR = "error"
    FAILED = "failed"
    SUCCESS = "success"
    SKIPPED = "skipped"


class JobRun(models.Model):
    name = models.CharField(max_length=255)
    started_on = models.DateTimeField(auto_now_add=True)
    duration = models.DurationField(null=True)
    state = models.CharField(
        max_length=12, choices=RunState.choices, default=RunState.NOT_STARTED
    )


class ActionRun(models.Model):
    name = models.CharField(max_length=255)
    jobrun = models.ForeignKey(
        JobRun, on_delete=models.CASCADE, related_name="actionruns"
    )
    started_on = models.DateTimeField(auto_now_add=True)
    duration = models.DurationField(null=True)
    state = models.CharField(
        max_length=12, choices=RunState.choices, default=RunState.NOT_STARTED
    )
    output = models.TextField(null=True)


class TestResult(models.Model):
    name = models.CharField(max_length=255)
    actionrun = models.ForeignKey(
        ActionRun, on_delete=models.CASCADE, related_name="testresults"
    )
    state = models.CharField(
        max_length=12, choices=RunState.choices, default=RunState.NOT_STARTED
    )
    duration = models.DurationField()
    output = models.TextField(null=True)

django_cd/views.py
""""""

# Standard library modules.

# Third party modules.
from django.shortcuts import render
from django.apps import apps
from django.http import HttpResponse, HttpResponseBadRequest

# Local modules.
from .models import JobRun, RunState
from .tasks import run_job

# Globals and constants variables.
colors = {
    RunState.SUCCESS: "#198754",
    RunState.ERROR: "#6f42c1",
    RunState.FAILED: "#dc3545",
    RunState.SKIPPED: "#ffc107",
    RunState.RUNNING: "gray-600",
}


def index(request):
    app = apps.get_app_config("django_cd")

    return render(
        request,
        "django_cd/index.html",
        context={
            "available_jobs": app.jobs.keys(),
        },
    )


def jobrun(request, id):
    jobrun = JobRun.objects.get(pk=id)
    return render(request, "django_cd/jobrun.html", context={"jobrun": jobrun})


def _always_n(iterable, n):
    it = iter(iterable)
    for _ in range(n):
        try:
            yield next(it)
        except StopIteration:
            yield None


def _create_jobruns_context(request):
    njobs = request.GET.get("njobs", 10)
    app = apps.get_app_config("django_cd")

    jobnames = dict(
        (n, n)
        for n in JobRun.objects.order_by("-started_on")
        .values_list("name", flat=True)
        .all()
    ).keys()

    rows = []
    for name in jobnames:
        runs = _always_n(
            JobRun.objects.filter(name=name)
            .order_by("-started_on")
            .values_list("id", "started_on", "state", named=True)[:njobs],
            njobs,
        )

        job = app.jobs.get(name)
        nextrun = job.nextrun if job is not None else None

        rows.append([name, runs, nextrun])

    return {
        "njobs": njobs,
        "rows": rows,
        "colwidth": int(85 / (njobs + 1)),
    }


def jobruns(request):
    return render(
        request,
        "django_cd/jobruns.html",
        context=_create_jobruns_context(request),
    )


def runjob(request):
    app = apps.get_app_config("django_cd")
    name = request.POST.get("jobname")
    job = app.jobs.get(name)

    if job is None:
        return HttpResponseBadRequest()

    run_job.schedule((job,), delay=0)
    return HttpResponse(status=204, headers={"HX-Refresh": "true"})

django_cd/templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Continuous deployment</title>

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    {% bootstrap_css %}

    {% block styles %}{% endblock %}
</head>

<body>
    <main role="main">
        <div class="container px-lg-3">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <!-- Scripts -->
    {% bootstrap_javascript %}
    <script src="https://cdn.plot.ly/plotly-2.1.0.min.js"></script>
    <script src="https://unpkg.com/htmx.org@1.4.1"></script>

    <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    });

    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    });
    </script>

    {% block scripts %}{% endblock %}
</body>
</html>

django_cd/templates/django_cd/index.html
{% extends "base.html" %}

{% block styles %}
<style>
.btn-circle {
    width: 30px;
    height: 30px;
    text-align: center;
    padding: 6px 0;
    font-size: 12px;
    line-height: 1.428571429;
    border-radius: 15px;
    }
</style>
{% endblock %}

{% block content %}
<h2>Continuous deployment</h2>

{% if available_jobs %}
<div class="d-inline-flex align-items-center my-3">
    <span class="text-nowrap">Job</span>
    <select class="form-select form-select-sm mx-2" name="jobname">
        {% for name in available_jobs %}
        <option value="{{ name }}">{{ name }}</option>
        {% endfor %}
    </select>
    <button type="button"
            class="btn btn-primary btn-sm text-nowrap"
            hx-post="{% url 'django_cd:runjob' %}"
            hx-include="[name='jobname']">
        Force run
    </button>
</div>
{% endif %}

<div hx-get="{% url 'django_cd:jobruns' %}" hx-trigger="load, every 600s">
    <div class="htmx-indicator spinner-border m-2" role="status"></div>
</div>
{% endblock %}

django_cd/templates/django_cd/jobrun.html
{% extends "base.html" %}
{% load djangocd_extras %}

{% block content %}
<h3>#{{ jobrun.id }}: {{ jobrun.name }}</h3>
<p>{{ jobrun.state|state_adjective|title }} since {{ jobrun.started_on|timesince }}</p>

<div class="accordion pt-3">
    {% for actionrun in jobrun.actionruns.all %}
        <div class="accordion-item">
            <h2 class="accordion-header" id="panel-header-{{ actionrun.id }}">
                <button class="accordion-button collapsed"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#panel-body-{{ actionrun.id }}"
                        aria-expanded="false"
                        aria-controls="panel-body-{{ actionrun.id }}">
                    #{{ forloop.counter }}: {{ actionrun.name }}
                    <span class="badge bg{{ actionrun.state|state_style }} mx-1">{{ actionrun.state }}</span>
                </button>
            </h2>
            <div id="panel-body-{{ actionrun.id }}"
                    class="accordion-collapse collapse"
                    aria-labelledby="panel-header-{{ actionrun.id }}">
                <div class="accordion-body">
                    <p class="text-end">
                        <i class="bi bi-clock-history mx-2"></i> {{ actionrun.duration|duration }}
                    </p>

                    {% if actionrun.testresults.count > 0 %}
                    <p class="text-end">
                        <i class="bi bi-clipboard-check"></i> {{ actionrun|testresult_summary }}
                    </p>
                    {% endif %}

                    <pre><code>{{ actionrun.output|linebreaks }}</code></pre>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

django_cd/templates/django_cd/jobrun_report.html
{% load djangocd_extras %}

{% for actionrun in jobrun.actionruns.all %}
    <h2>#{{ forloop.counter }}: {{ actionrun.name }} ({{ actionrun.state }})</h2>
    <p>{{ jobrun.started_on }} - {{ actionrun.duration|duration }}<p>

    {% if actionrun.testresults.count > 0 %}{{ actionrun|testresult_summary }}{% endif %}

    <pre><code>{{ actionrun.output|linebreaks }}</code></pre>
{% endfor %}

django_cd/templates/django_cd/jobruns.html
{% load djangocd_extras %}

<table class="table table-striped align-middle">
    <thead>
        <tr class="">
            <th scope="col">Job name</th>

            {% for index in njobs|listrange:1 reversed %}
            <th scope="col"
                    class="text-center {% if index > 3 %}d-none d-md-table-cell{% endif %}"
                    style="width: {{ colwidth }}%">
                {{ index }}
            </th>
            {% endfor %}

            <th scope="col"
                class="text-center"
                style="width: {{ colwidth }}%">Next</th>
        </tr>
    </thead>
    <tbody>
        {% for name, jobruns, nextrun in rows %}
        <tr>
            <td>{{ name }}</td>

            {% for jobrun in jobruns reversed %}
            <td class="text-center {% if forloop.counter0 < 7 %}d-none d-md-table-cell{% endif %}">
                {%if jobrun.id %}
                <a class="btn btn-circle btn{{ jobrun.state|state_style }}"
                    href="{% url 'django_cd:jobrun' jobrun.id %}"
                    data-bs-toggle="tooltip"
                    data-bs-placement="top"
                    title="Started on: {{ jobrun.started_on }}">
                    {% if jobrun.state == "success" %}
                        <i class="bi bi-check-lg"></i>
                    {% elif jobrun.state == "running" %}
                        <i class="bi bi-hourglass-split"></i>
                    {% elif jobrun.state == "error" %}
                        <i class="bi bi-exclamation-lg"></i>
                    {% endif %}
                </a>
                {% endif %}
            </td>
            {% endfor %}

            <td class="text-center">
                {% if nextrun %}
                <span class="d-inline-block"
                        tabindex="0"
                        data-bs-toggle="tooltip"
                        data-bs-placement="top"
                        title="Scheduled for: {{ nextrun }}">
                    <button class="btn btn-circle btn-secondary" type="button" disabled></button>
                </span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>